
SELECT * FROM MEMBER;
DESC MEMBER;


INSERT INTO MEMBER(NAME,birthday) VALUES('디지몬','91-07-05');
INSERT INTO MEMBER(NAME,birthday) VALUES('포켓몬','88-04-05');


SELECT * FROM MEMBER WHERE SUBSTR(birthday,4,2) IN(07,08,09);